apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app
  namespace: default
  labels:
    app: example-app
spec:
  selector:
    matchLabels:
      app: example-app
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: example-app
    spec:      
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: example-app         
          env:                        
            - name: APP-NAME
              value: "hw"
          ports:
            - containerPort: 8084
