apiVersion: v1
kind: Service
metadata:
  name: example-app
  labels:
    app: example-app
spec:
  selector:
    app: example-app
  type: NodePort
  ports:
    - port: 8084
      targetPort: 8084
      nodePort: {{ .Values.service.port }}
